package jmdict.enums

enum class PartOfSpeechEnum(override val code: String, override val description: String) : InformationEnum {
    ADJECTIVE_F("adj-f", "noun or verb acting prenominally"),
    ADJECTIVE_I("adj-i", "adjective (keiyoushi)"),
    ADJECTIVE_IX("adj-ix", "adjective (keiyoushi) - yoi/ii class"),
    ADJECTIVE_KARI("adj-kari", "'kari' adjective (archaic)"),
    KU_ADJECTIVE("adj-ku", "'ku' adjective (archaic)"),
    ADJECTIVE_NA("adj-na", "adjectival nouns or quasi-adjectives (keiyodoshi)"),
    NARI_ADJECTIVE("adj-nari", "archaic/formal form of na-adjective"),
    ADJECTIVE_NO("adj-no", "nouns which may take the genitive case particle 'no'"),
    ADJECTIVE_PN("adj-pn", "pre-noun adjectival (rentaishi)"),
    SHIKU_ADJECTIVE("adj-shiku", "'shiku' adjective (archaic)"),
    ADJECTIVE_T("adj-t", "'taru' adjective"),
    ADVERB("adv", "adverb (fukushi)"),
    ADVERB_TAKING_TO("adv-to", "adverb taking the 'to' particle"),
    AUXILIARY("aux", "auxiliary"),
    AUXILIARY_ADJECTIVE("aux-adj", "auxiliary adjective"),
    AUXILIARY_VERB("aux-v", "auxiliary verb"),
    CONJUNCTION("conj", "conjunction"),
    COPULA("cop-da", "copula"),
    COUNTER("ctr", "counter"),
    EXPRESSION("exp", "expressions (phrases, clauses, etc.)"),
    INTERJECTION("int", "interjection (kandoushi)"),
    NOUN("n", "noun (common) (futsuumeishi)"),
    NOUN_ADVERBIAL("n-adv", "adverbial noun (fukushitekimeishi)"),
    NOUN_PROPER("n-pr", "proper noun"),
    NOUN_PREFIX("n-pref", "noun, used as a prefix"),
    NOUN_SUFFIX("n-suf", "noun, used as a suffix"),
    NOUN_TEMPORAL("n-t", "noun (temporal) (jisoumeishi)"),
    NUMERIC("num", "numeric"),
    PRONOUN("pn", "pronoun"),
    PREFIX("pref", "prefix"),
    PARTICLE("prt", "particle"),
    SUFFIX("suf", "suffix"),
    UNCLASSIFIED("unc", "unclassified"),
    UNSPECIFIED_VERB("v-unspec", "verb unspecified"),
    ICHIDAN("v1", "Ichidan verb"),
    ICHIDAN_KURERU("v1-s", "Ichidan verb - kureru special class"),
    YODAN_RU("v4r", "Yodan verb with 'ru' ending (archaic)"),
    YODAN_KU_UPPER_ARCHAIC("v4k", "Yodan verb with 'ku' ending (archaic)"),
    YODAN_GU_UPPER_ARCHAIC("v4g", "Yodan verb with 'gu' ending (archaic)"),
    YODAN_SU_UPPER_ARCHAIC("v4s", "Yodan verb with 'su' ending (archaic)"),
    YODAN_TSU_UPPER_ARCHAIC("v4t", "Yodan verb with 'tsu' ending (archaic)"),
    YODAN_NU_UPPER_ARCHAIC("v4n", "Yodan verb with 'nu' ending (archaic)"),
    YODAN_BU_UPPER_ARCHAIC("v4b", "Yodan verb with 'bu' ending (archaic)"),
    YODAN_MU_UPPER_ARCHAIC("v4m", "Yodan verb with 'mu' ending (archaic)"),
    NIDAN_KU_UPPER_ARCHAIC("v2k-k", "Nidan verb (upper class) with 'ku' ending (archaic)"),
    NIDAN_GU_UPPER_ARCHAIC("v2g-k", "Nidan verb (upper class) with 'gu' ending (archaic)"),
    NIDAN_TSU_UPPER_ARCHAIC("v2t-k", "Nidan verb (upper class) with 'tsu' ending (archaic)"),
    NIDAN_DZU_UPPER_ARCHAIC("v2d-k", "Nidan verb (upper class) with 'dzu' ending (archaic)"),
    NIDAN_HU_FU_UPPER_ARCHAIC("v2h-k", "Nidan verb (upper class) with 'hu/fu' ending (archaic)"),
    NIDAN_BU_UPPER_ARCHAIC("v2b-k", "Nidan verb (upper class) with 'bu' ending (archaic)"),
    NIDAN_MU_UPPER_ARCHAIC("v2m-k", "Nidan verb (upper class) with 'mu' ending (archaic)"),
    NIDAN_YU_UPPER_ARCHAIC("v2y-k", "Nidan verb (upper class) with 'yu' ending (archaic)"),
    NIDAN_RU_UPPER_ARCHAIC("v2r-k", "Nidan verb (upper class) with 'ru' ending (archaic)"),
    NIDAN_KU_LOWER_ARCHAIC("v2k-s", "Nidan verb (lower class) with 'ku' ending (archaic)"),
    NIDAN_GU_LOWER_ARCHAIC("v2g-s", "Nidan verb (lower class) with 'gu' ending (archaic)"),
    NIDAN_SU_LOWER_ARCHAIC("v2s-s", "Nidan verb (lower class) with 'su' ending (archaic)"),
    NIDAN_ZU_LOWER_ARCHAIC("v2z-s", "Nidan verb (lower class) with 'zu' ending (archaic)"),
    NIDAN_TSU_LOWER_ARCHAIC("v2t-s", "Nidan verb (lower class) with 'tsu' ending (archaic)"),
    NIDAN_DZU_LOWER_ARCHAIC("v2d-s", "Nidan verb (lower class) with 'dzu' ending (archaic)"),
    NIDAN_NU_LOWER_ARCHAIC("v2n-s", "Nidan verb (lower class) with 'nu' ending (archaic)"),
    NIDAN_HU_FU_LOWER_ARCHAIC("v2h-s", "Nidan verb (lower class) with 'hu/fu' ending (archaic)"),
    NIDAN_BU_LOWER_ARCHAIC("v2b-s", "Nidan verb (lower class) with 'bu' ending (archaic)"),
    NIDAN_MU_LOWER_ARCHAIC("v2m-s", "Nidan verb (lower class) with 'mu' ending (archaic)"),
    NIDAN_YU_LOWER_ARCHAIC("v2y-s", "Nidan verb (lower class) with 'yu' ending (archaic)"),
    NIDAN_RU_LOWER_ARCHAIC("v2r-s", "Nidan verb (lower class) with 'ru' ending (archaic)"),
    NIDAN_U_WE_LOWER_ARCHAIC("v2w-s", "Nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)"),
    NIDAN_U("v2a-s", "Nidan verb with 'u' ending (archaic)"),
    NIDAN_HU_FU("v4h", "Yodan verb with 'hu/fu' ending (archaic)"),
    GODAN_ARU("v5aru", "Godan verb - -aru special class"),
    GODAN_BU("v5b", "Godan verb with 'bu' ending"),
    GODAN_GU("v5g", "Godan verb with 'gu' ending"),
    GODAN_KU("v5k", "Godan verb with 'ku' ending"),
    GODAN_IKU_YUKU("v5k-s", "Godan verb - Iku/Yuku special class"),
    GODAN_MU("v5m", "Godan verb with 'mu' ending"),
    GODAN_NU("v5n", "Godan verb with 'nu' ending"),
    GODAN_RU("v5r", "Godan verb with 'ru' ending"),
    GODAN_RU_IRREGULAR("v5r-i", "Godan verb with 'ru' ending (irregular verb)"),
    GODAN_SU("v5s", "Godan verb with 'su' ending"),
    GODAN_TSU("v5t", "Godan verb with 'tsu' ending"),
    GODAN_U("v5u", "Godan verb with 'u' ending"),
    GODAN_U_SPECIAL("v5u-s", "Godan verb with 'u' ending (special class)"),
    GODAN_URU("v5uru", "Godan verb - Uru old class verb (old form of Eru)"),
    INTRANSIVIVE_VERB("vi", "intransitive verb"),
    KURU_VERB("vk", "Kuru verb - special class"),
    IRREGULAR_NU_VERB("vn", "irregular nu verb"),
    IRREGULAR_RU_RI_END_VERB("vr", "irregular ru verb, plain form ends with -ri"),
    NOUN_PARTICIPLE_SURU("vs", "noun or participle which takes the aux. verb suru"),
    SU_VERB("vs-c", "su verb - precursor to the modern suru"),
    SURU_VERB_INCLUDED("vs-i", "suru verb - included"),
    SURU_VERB_SPECIAL("vs-s", "suru verb - special class"),
    TRANSITIVE_VERB("vt", "transitive verb"),
    GODAN_ZURU("vz", "Ichidan verb - zuru verb (alternative form of -jiru verbs)");

    companion object {
        fun from(value: String) = try {
            values().first { it.code == value || it.description == value }
        } catch (e: NoSuchElementException) {
            throw NoSuchElementException(e.message + " $value", e.cause)
        }
    }
}
